name: Build

on:
    workflow_dispatch:
    
jobs:
    build:
      name: Build
      env:
        NUPKG_MAJOR: 3.1
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Build
        run: msbuild /r /t:Build /p:Configuration=Release .\ZXing.Net.Mobile.sln
      - name: Package NuGets
        run: |
          $pkgVer = ($env:NUPKG_MAJOR + "-alpha" + $env:GITHUB_RUN_ID)
          if ($env:GITHUB_EVENT_NAME -eq "release") {
            $pkgVer = $env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
          }
          New-Item -ItemType Directory -Force -Path .\artifacts
          msbuild /t:Pack /p:Configuration=Release /p:PackageOutputPath=..\artifacts /p:PackageVersion=$pkgVer /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg .\ZXing.Net.Mobile\ZXing.Net.Mobile.csproj
          msbuild /t:Pack /p:Configuration=Release /p:PackageOutputPath=..\artifacts /p:PackageVersion=$pkgVer /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg .\ZXing.Net.Mobile.Forms\ZXing.Net.Mobile.Forms.csproj
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: .\artifacts
